remote_theme: jekyll/minima
minima:
  skin: light
  social_links:
    - title: Vincent Pisztora GitHub
      icon: github
      url: "https://github.com/VincentPisztora"
    - title: Vincent Pisztora LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/vincent-pisztora-0b774728"

title: Vincent Pisztora

author: Vincent Pisztora
  
